# Generated by Django 6.0.5 on 2026-05-16 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_payment_id', models.CharField(max_length=128, unique=True)),
                ('amount_paise', models.PositiveIntegerField()),
                ('paid_at', models.DateTimeField()),
                ('receipt_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(unique=True)),
                ('price_monthly_paise', models.PositiveIntegerField(help_text='INR paise')),
                ('price_yearly_paise', models.PositiveIntegerField(help_text='INR paise')),
                ('ops_per_day', models.IntegerField(help_text='-1 = unlimited')),
                ('max_file_mb', models.PositiveIntegerField()),
                ('max_files', models.IntegerField(help_text='-1 = unlimited')),
                ('has_batch', models.BooleanField(default=False)),
                ('has_ai', models.BooleanField(default=False)),
                ('has_api', models.BooleanField(default=False)),
                ('has_esign_unlimited', models.BooleanField(default=False)),
                ('has_team', models.BooleanField(default=False)),
                ('team_seats', models.PositiveIntegerField(default=1)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_subscription_id', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('cancelled', 'Cancelled')], default='trialing', max_length=20)),
                ('is_annual', models.BooleanField(default=False)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
            ],
        ),
    ]
