"""Tool registry — all MVP tools."""

TOOLS = [
    {
        "slug": "compress-pdf",
        "name": "Compress PDF",
        "description": "Reduce PDF file size without losing quality.",
        "category": "pdf",
        "url_name": "tools:compress-pdf",
        "template": "pages/tools/compress_pdf.jinja",
        "is_live": True,
        "extensions": {".pdf"},
        "option_fields": ["quality"],
        "seo": {
            "title": "Compress PDF Online Free — Reduce PDF Size | SD-Toolx",
            "description": "Compress PDF files online for free. Reduce size up to 90%. No signup.",
            "h1": "Compress PDF",
        },
    },
    {
        "slug": "merge-pdf",
        "name": "Merge & Compress PDF",
        "description": "Combine multiple PDFs into one smaller file — merged and compressed automatically.",
        "category": "pdf",
        "url_name": "tools:merge-pdf",
        "template": "pages/tools/merge_pdf.jinja",
        "is_live": True,
        "extensions": {".pdf"},
        "multiple": True,
        "min_files": 2,
        "option_fields": ["order", "quality"],
        "seo": {
            "title": "Merge & Compress PDF Online Free | SD-Toolx",
            "description": "Merge PDF files and compress in one step. Smaller output, free, no watermark.",
            "h1": "Merge & Compress PDF",
        },
    },
    {
        "slug": "split-pdf",
        "name": "Split PDF",
        "description": "Extract pages from a PDF.",
        "category": "pdf",
        "url_name": "tools:split-pdf",
        "template": "pages/tools/split_pdf.jinja",
        "is_live": True,
        "extensions": {".pdf"},
        "option_fields": ["pages", "mode"],
        "seo": {"title": "Split PDF Online Free | SD-Toolx", "h1": "Split PDF"},
    },
    {
        "slug": "rotate-pdf",
        "name": "Rotate PDF",
        "description": "Rotate PDF pages 90°, 180°, or 270°.",
        "category": "pdf",
        "url_name": "tools:rotate-pdf",
        "template": "pages/tools/rotate_pdf.jinja",
        "is_live": True,
        "extensions": {".pdf"},
        "option_fields": ["angle"],
        "seo": {"title": "Rotate PDF Online Free | SD-Toolx", "h1": "Rotate PDF"},
    },
    {
        "slug": "pdf-to-jpg",
        "name": "PDF to JPG",
        "description": "Convert PDF pages to JPG images.",
        "category": "pdf",
        "url_name": "tools:pdf-to-jpg",
        "template": "pages/tools/pdf_to_jpg.jinja",
        "is_live": True,
        "extensions": {".pdf"},
        "option_fields": ["dpi"],
        "seo": {"title": "PDF to JPG Converter Free | SD-Toolx", "h1": "PDF to JPG"},
    },
    {
        "slug": "img-to-pdf",
        "name": "JPG to PDF",
        "description": "Convert images to a single PDF.",
        "category": "pdf",
        "url_name": "tools:img-to-pdf",
        "template": "pages/tools/img_to_pdf.jinja",
        "is_live": True,
        "extensions": {".jpg", ".jpeg", ".png", ".webp"},
        "multiple": True,
        "option_fields": ["page_size"],
        "seo": {"title": "JPG to PDF Converter Free | SD-Toolx", "h1": "JPG to PDF"},
    },
    {
        "slug": "word-to-pdf",
        "name": "Word to PDF",
        "description": "Convert DOCX to PDF online.",
        "category": "pdf",
        "url_name": "tools:word-to-pdf",
        "template": "pages/tools/word_to_pdf.jinja",
        "is_live": True,
        "extensions": {".docx", ".doc"},
        "seo": {"title": "Word to PDF Converter Free | SD-Toolx", "h1": "Word to PDF"},
    },
    {
        "slug": "compress-image",
        "name": "Compress Image",
        "description": "Shrink images up to 90% smaller. JPG, PNG, WebP.",
        "category": "image",
        "url_name": "tools:compress-image",
        "template": "pages/tools/compress_image.jinja",
        "is_live": True,
        "extensions": {".jpg", ".jpeg", ".png", ".webp"},
        "option_fields": ["mode", "output_format"],
        "seo": {
            "title": "Compress Image Lossless Online Free | SD-Toolx",
            "h1": "Compress Image",
        },
    },
    {
        "slug": "sign-pdf",
        "name": "Sign PDF",
        "description": "Add your signature to any PDF — free.",
        "category": "pdf",
        "url_name": "tools:sign-pdf",
        "template": "pages/tools/sign_pdf.jinja",
        "is_live": True,
        "extensions": {".pdf", ".png", ".jpg", ".jpeg"},
        "multiple": True,
        "option_fields": ["signature_data", "page", "x", "y", "width", "height"],
        "seo": {"title": "Sign PDF Online Free — E-Signature | SD-Toolx", "h1": "Sign PDF"},
    },
    {
        "slug": "pdf-to-word",
        "name": "PDF to Word",
        "description": "Convert PDF to editable DOCX.",
        "category": "pdf",
        "url_name": "tools:pdf-to-word",
        "template": "pages/tools/pdf_to_word.jinja",
        "is_live": True,
        "extensions": {".pdf"},
        "seo": {"title": "PDF to Word Converter Free | SD-Toolx", "h1": "PDF to Word"},
    },
    {
        "slug": "reorder-pdf",
        "name": "Reorder PDF Pages",
        "description": "Drag pages to reorder your PDF.",
        "category": "pdf",
        "url_name": "tools:reorder-pdf",
        "template": "pages/tools/reorder_pdf.jinja",
        "is_live": True,
        "extensions": {".pdf"},
        "option_fields": ["order", "delete_pages"],
        "seo": {"title": "Reorder PDF Pages Online Free | SD-Toolx", "h1": "Reorder PDF"},
    },
    {
        "slug": "delete-pdf-pages",
        "name": "Delete PDF Pages",
        "description": "Remove unwanted pages from a PDF.",
        "category": "pdf",
        "url_name": "tools:delete-pdf-pages",
        "template": "pages/tools/delete_pdf_pages.jinja",
        "is_live": True,
        "extensions": {".pdf"},
        "option_fields": ["delete_pages"],
        "seo": {"title": "Delete PDF Pages Online Free | SD-Toolx", "h1": "Delete PDF Pages"},
    },
    {
        "slug": "unlock-pdf",
        "name": "Unlock PDF",
        "description": "Remove password protection from a PDF you own.",
        "category": "pdf",
        "url_name": "tools:unlock-pdf",
        "template": "pages/tools/unlock_pdf.jinja",
        "is_live": True,
        "extensions": {".pdf"},
        "option_fields": ["password"],
        "seo": {"title": "Unlock PDF Online Free | SD-Toolx", "h1": "Unlock PDF"},
    },
    {
        "slug": "protect-pdf",
        "name": "Protect PDF",
        "description": "Add password protection to your PDF.",
        "category": "pdf",
        "url_name": "tools:protect-pdf",
        "template": "pages/tools/protect_pdf.jinja",
        "is_live": True,
        "extensions": {".pdf"},
        "option_fields": ["password"],
        "seo": {"title": "Protect PDF with Password Free | SD-Toolx", "h1": "Protect PDF"},
    },
    {
        "slug": "remove-background",
        "name": "Remove Background",
        "description": "AI removes the background — transparent PNG output.",
        "category": "image",
        "url_name": "tools:remove-background",
        "template": "pages/tools/remove_background.jinja",
        "is_live": True,
        "extensions": {".jpg", ".jpeg", ".png", ".webp"},
        "seo": {
            "title": "Remove Background from Image Free | SD-Toolx",
            "h1": "Remove Background",
        },
    },
    {
        "slug": "ai-summarize-pdf",
        "name": "AI PDF Summarizer",
        "description": "Get bullet points and a short summary of any PDF.",
        "category": "pdf",
        "url_name": "tools:ai-summarize-pdf",
        "template": "pages/tools/ai_summarize_pdf.jinja",
        "is_live": True,
        "extensions": {".pdf"},
        "seo": {
            "title": "AI PDF Summarizer Free | SD-Toolx",
            "h1": "AI PDF Summarizer",
        },
    },
    {
        "slug": "qr-generator",
        "name": "QR Code Generator",
        "description": "Create QR codes for URL, UPI, WhatsApp, WiFi.",
        "category": "utility",
        "url_name": "tools:qr-generator",
        "template": "pages/tools/qr_generator.jinja",
        "is_live": True,
        "no_upload": True,
        "option_fields": ["text", "qr_type", "size"],
        "seo": {"title": "QR Code Generator Free — UPI & URL | SD-Toolx", "h1": "QR Generator"},
    },
    # ── Phase 5 tools ────────────────────────────────────────────────
    {
        "slug": "excel-to-pdf",
        "name": "Excel to PDF",
        "description": "Convert Excel spreadsheets (.xlsx, .xls) to PDF.",
        "category": "pdf",
        "url_name": "tools:excel-to-pdf",
        "template": "pages/tools/excel_to_pdf.jinja",
        "is_live": True,
        "extensions": {".xlsx", ".xls", ".ods"},
        "seo": {"title": "Excel to PDF Converter Free | SD-Toolx", "h1": "Excel to PDF"},
    },
    {
        "slug": "ppt-to-pdf",
        "name": "PowerPoint to PDF",
        "description": "Convert PPTX presentations to PDF.",
        "category": "pdf",
        "url_name": "tools:ppt-to-pdf",
        "template": "pages/tools/ppt_to_pdf.jinja",
        "is_live": True,
        "extensions": {".pptx", ".ppt", ".odp"},
        "seo": {"title": "PowerPoint to PDF Free | SD-Toolx", "h1": "PowerPoint to PDF"},
    },
    {
        "slug": "pdf-to-excel",
        "name": "PDF to Excel",
        "description": "Extract tables from PDF into an Excel spreadsheet.",
        "category": "pdf",
        "url_name": "tools:pdf-to-excel",
        "template": "pages/tools/pdf_to_excel.jinja",
        "is_live": True,
        "extensions": {".pdf"},
        "seo": {"title": "PDF to Excel Converter Free | SD-Toolx", "h1": "PDF to Excel"},
    },
    {
        "slug": "pdf-to-ppt",
        "name": "PDF to PowerPoint",
        "description": "Convert PDF pages into a PowerPoint presentation.",
        "category": "pdf",
        "url_name": "tools:pdf-to-ppt",
        "template": "pages/tools/pdf_to_ppt.jinja",
        "is_live": True,
        "extensions": {".pdf"},
        "seo": {"title": "PDF to PowerPoint Free | SD-Toolx", "h1": "PDF to PowerPoint"},
    },
    {
        "slug": "watermark-pdf",
        "name": "Watermark PDF",
        "description": "Add a custom text watermark to every page of your PDF.",
        "category": "pdf",
        "url_name": "tools:watermark-pdf",
        "template": "pages/tools/watermark_pdf.jinja",
        "is_live": True,
        "extensions": {".pdf"},
        "option_fields": ["text", "opacity", "rotation", "color"],
        "seo": {"title": "Add Watermark to PDF Free | SD-Toolx", "h1": "Watermark PDF"},
    },
    {
        "slug": "repair-pdf",
        "name": "Repair PDF",
        "description": "Fix and recover corrupted or broken PDF files.",
        "category": "pdf",
        "url_name": "tools:repair-pdf",
        "template": "pages/tools/repair_pdf.jinja",
        "is_live": True,
        "extensions": {".pdf"},
        "seo": {"title": "Repair Corrupt PDF Free | SD-Toolx", "h1": "Repair PDF"},
    },
    {
        "slug": "redact-pdf",
        "name": "Redact PDF",
        "description": "Permanently black out sensitive text in your PDF.",
        "category": "pdf",
        "url_name": "tools:redact-pdf",
        "template": "pages/tools/redact_pdf.jinja",
        "is_live": True,
        "extensions": {".pdf"},
        "option_fields": ["search_terms"],
        "seo": {"title": "Redact PDF Text Free | SD-Toolx", "h1": "Redact PDF"},
    },
    {
        "slug": "compare-pdf",
        "name": "Compare PDF",
        "description": "Side-by-side comparison of two PDF files.",
        "category": "pdf",
        "url_name": "tools:compare-pdf",
        "template": "pages/tools/compare_pdf.jinja",
        "is_live": True,
        "extensions": {".pdf"},
        "multiple": True,
        "min_files": 2,
        "seo": {"title": "Compare Two PDFs Side-by-Side Free | SD-Toolx", "h1": "Compare PDF"},
    },
    {
        "slug": "fill-pdf-form",
        "name": "Fill PDF Form",
        "description": "Fill interactive PDF form fields online.",
        "category": "pdf",
        "url_name": "tools:fill-pdf-form",
        "template": "pages/tools/fill_pdf_form.jinja",
        "is_live": True,
        "extensions": {".pdf"},
        "option_fields": ["field_values"],
        "seo": {"title": "Fill PDF Form Online Free | SD-Toolx", "h1": "Fill PDF Form"},
    },
    {
        "slug": "ocr",
        "name": "OCR — Extract Text",
        "description": "Extract text from scanned PDFs and images.",
        "category": "pdf",
        "url_name": "tools:ocr",
        "template": "pages/tools/ocr.jinja",
        "is_live": True,
        "extensions": {".pdf", ".jpg", ".jpeg", ".png", ".tiff", ".tif", ".bmp"},
        "option_fields": ["lang"],
        "seo": {"title": "OCR — Extract Text from PDF & Images Free | SD-Toolx", "h1": "OCR Text Extraction"},
    },
    {
        "slug": "ai-translate-pdf",
        "name": "AI Translate PDF",
        "description": "Translate PDF to Hindi, Tamil, Telugu, Spanish and more.",
        "category": "pdf",
        "url_name": "tools:ai-translate-pdf",
        "template": "pages/tools/ai_translate_pdf.jinja",
        "is_live": True,
        "extensions": {".pdf"},
        "option_fields": ["target_lang"],
        "seo": {"title": "AI PDF Translator Free | SD-Toolx", "h1": "AI Translate PDF"},
    },
    {
        "slug": "ai-extract-data",
        "name": "AI Extract Data",
        "description": "AI extracts names, dates, amounts, and key facts from documents.",
        "category": "pdf",
        "url_name": "tools:ai-extract-data",
        "template": "pages/tools/ai_extract_data.jinja",
        "is_live": True,
        "extensions": {".pdf"},
        "seo": {"title": "AI Data Extractor from PDF Free | SD-Toolx", "h1": "AI Extract Data"},
    },
    {
        "slug": "upscale-image",
        "name": "Upscale Image",
        "description": "Enlarge images 2x or 4x using high-quality resampling.",
        "category": "image",
        "url_name": "tools:upscale-image",
        "template": "pages/tools/upscale_image.jinja",
        "is_live": True,
        "extensions": {".jpg", ".jpeg", ".png", ".webp", ".bmp"},
        "option_fields": ["scale"],
        "seo": {"title": "Upscale Image Free — 2x 4x Enlarger | SD-Toolx", "h1": "Upscale Image"},
    },
    {
        "slug": "word-counter",
        "name": "Word Counter",
        "description": "Count words, characters, sentences and reading time.",
        "category": "utility",
        "url_name": "tools:word-counter",
        "template": "pages/tools/word_counter.jinja",
        "is_live": True,
        "extensions": {".pdf", ".docx", ".doc", ".txt"},
        "no_upload": False,
        "option_fields": ["text"],
        "seo": {"title": "Word Counter Free — Characters & Reading Time | SD-Toolx", "h1": "Word Counter"},
    },
    # ── Phase 6 tools ────────────────────────────────────────────────
    {
        "slug": "resize-image",
        "name": "Resize Image",
        "description": "Resize images by pixels or percentage. Lock aspect ratio.",
        "category": "image",
        "url_name": "tools:resize-image",
        "template": "pages/tools/resize_image.jinja",
        "is_live": True,
        "extensions": {".jpg", ".jpeg", ".png", ".webp", ".bmp", ".gif"},
        "option_fields": ["mode", "width", "height", "percent", "lock_ratio"],
        "seo": {"title": "Resize Image Online Free | SD-Toolx", "h1": "Resize Image"},
    },
    {
        "slug": "convert-image",
        "name": "Convert Image",
        "description": "Convert images between JPG, PNG, WebP, BMP, GIF formats.",
        "category": "image",
        "url_name": "tools:convert-image",
        "template": "pages/tools/convert_image.jinja",
        "is_live": True,
        "extensions": {".jpg", ".jpeg", ".png", ".webp", ".bmp", ".gif"},
        "option_fields": ["to_format"],
        "seo": {"title": "Convert Image Format Free | SD-Toolx", "h1": "Convert Image"},
    },
    {
        "slug": "watermark-image",
        "name": "Watermark Image",
        "description": "Add text watermark to any image.",
        "category": "image",
        "url_name": "tools:watermark-image",
        "template": "pages/tools/watermark_image.jinja",
        "is_live": True,
        "extensions": {".jpg", ".jpeg", ".png", ".webp", ".bmp"},
        "option_fields": ["text", "opacity", "position"],
        "seo": {"title": "Add Watermark to Image Free | SD-Toolx", "h1": "Watermark Image"},
    },
    {
        "slug": "id-photo",
        "name": "Passport / ID Photo",
        "description": "Resize photo to Aadhaar, PAN, passport, visa standard sizes.",
        "category": "image",
        "url_name": "tools:id-photo",
        "template": "pages/tools/id_photo.jinja",
        "is_live": True,
        "extensions": {".jpg", ".jpeg", ".png", ".webp"},
        "option_fields": ["preset", "bg_color"],
        "seo": {"title": "Passport & ID Photo Maker Free | SD-Toolx", "h1": "Passport & ID Photo"},
    },
    {
        "slug": "ai-grammar-check",
        "name": "AI Grammar Check PDF",
        "description": "AI proofreads your PDF and corrects grammar and spelling.",
        "category": "pdf",
        "url_name": "tools:ai-grammar-check",
        "template": "pages/tools/ai_grammar_check.jinja",
        "is_live": True,
        "extensions": {".pdf"},
        "seo": {"title": "AI Grammar Check PDF Free | SD-Toolx", "h1": "AI Grammar Check"},
    },
    {
        "slug": "barcode-generator",
        "name": "Barcode Generator",
        "description": "Generate Code128, EAN-13, EAN-8 and other barcodes.",
        "category": "utility",
        "url_name": "tools:barcode-generator",
        "template": "pages/tools/barcode_generator.jinja",
        "is_live": True,
        "no_upload": True,
        "option_fields": ["text", "barcode_type"],
        "seo": {"title": "Barcode Generator Free | SD-Toolx", "h1": "Barcode Generator"},
    },
    {
        "slug": "url-shortener",
        "name": "URL Shortener",
        "description": "Shorten any URL to a compact sdtoolx.com/s/ link.",
        "category": "utility",
        "url_name": "tools:url-shortener",
        "template": "pages/tools/url_shortener.jinja",
        "is_live": True,
        "no_upload": True,
        "option_fields": ["url"],
        "seo": {"title": "URL Shortener Free | SD-Toolx", "h1": "URL Shortener"},
    },
]


def get_tool(slug: str) -> dict:
    for tool in TOOLS:
        if tool["slug"] == slug:
            return tool
    raise KeyError(slug)


def live_tools():
    return [t for t in TOOLS if t.get("is_live")]
