# Generated by Django 6.0.5 on 2026-05-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tooljob',
            name='options',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tooljob',
            name='preview_file',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
